### ISSUE TITLE
check assignment

### ISSUE THREAD

**Issue by AlekseiILitvinov** [AlekseiILitvinov/HomeworkDependencyInjection#1]
Рефактор контейнера я сделал не в фреймворке, а в моей реализации, в классе HomeworkContainerImplementation.

Реализован поиск по имени (можно добавить поиск описанию через contains()) и отображение "деталей". Самих деталей пока нет, это скорее заглушка - просто страница для одного объекта Auto, найденного по id.

**Comment by AlekseiILitvinov** [comment]
Добавил поиск по описанию

**Comment by coursar** [comment]
Назвать только надо было нормально )) а не `HomeworkContainerImplementation`.
